// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/dotamixer/doom/tool/doom-protoc/internal/compile"
	"github.com/dotamixer/doom/tool/doom-protoc/internal/config"
	"github.com/dotamixer/doom/tool/doom-protoc/internal/format"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	config := config.NewConfig()
	compiler := compile.NewCompiler(config)
	formatter := format.NewFormatter()
	app := NewApp(config, compiler, formatter)
	return app, nil
}
