// Code generated by protoc-gen-dm. DO NOT EDIT.
// source: com/app/greeter/v1/greeter_service.proto

package greeter

import (
	"google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.

var (
	ServiceName = "com.app.greeter.v1"
)

func NewGreeterServiceClientByDoom() (client GreeterServiceClient, err error) {
	var (
		conn *grpc.ClientConn
	)
	conn, err = grpc.Dial("consul://default/com.app.greeter.v1",
		grpc.WithInsecure())
	if err != nil {
		return
	}

	client = NewGreeterServiceClient(conn)
	return
}
